call plug#begin()
source ~/.vim/vimrc_module_plugins
call plug#end()

" vim-airline options
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
set laststatus=2

" tabs
set tabstop=2
set shiftwidth=2
set expandtab

" general settings
set background=dark
silent colorscheme hybrid
set backspace=indent,eol,start
set number
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" mappings
let mapleader=","
map ; :
nnoremap <silent><leader>/  :nohl<cr>
nnoremap <leader>ev         :e ~/.vimrc<cr>
nnoremap <leader>ep         :e ~/.vim/vimrc_module_plugins<cr>
nnoremap <cr>               :w<cr>
nnoremap <silent><space>    :bn<cr>
nnoremap <silent><s-space>  :bp<cr>
nnoremap <silent><backspace> :bd<cr>
nnoremap <silent><s-h>       :bp<cr>
nnoremap <silent><s-l>       :bn<cr>
inoremap ;; <end>;
inoremap ,, <end>,

" filetypes
au BufNewFile,BufRead *.ejs set filetype=html

" ctrlp settings
" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
